using System.IO;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Threading;
namespace DesktopBox;
internal sealed class Entry {
 public string Path {get;init;}=""; public string Name=>System.IO.Path.GetFileName(Path);public bool Exists=>File.Exists(Path)||Directory.Exists(Path);
 public string Type=>Directory.Exists(Path)?"文件夹":System.IO.Path.GetExtension(Path);public string Size {get{try{return File.Exists(Path)?new FileInfo(Path).Length.ToString("N0")+" B":"";}catch{return "";}}}public string Modified {get{try{return File.GetLastWriteTime(Path).ToString("yyyy-MM-dd HH:mm");}catch{return "";}}}
 public ImageSource? Icon=>ShellIcons.Get(Path);public override string ToString()=>Name;
}
internal sealed class BoxWindow:Window {
 readonly Program app; internal BoxConfig Config; readonly ListView entries=new();readonly TextBlock status=new(){TextWrapping=TextWrapping.Wrap,FontSize=11};readonly TextBlock title=new(){FontSize=17,FontWeight=FontWeights.SemiBold};FileSystemWatcher? watcher;readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromSeconds(2)};bool closing; readonly TextBox nameEditor=new(){FontSize=17,Visibility=Visibility.Collapsed,Foreground=Brushes.White,Background=new SolidColorBrush(Color.FromRgb(38,53,72)),Padding=new Thickness(2)}; readonly Grid titleHost=new(){HorizontalAlignment=HorizontalAlignment.Left,MinWidth=40}; readonly Border headerSurface=new(){Background=Brushes.Transparent,Margin=new Thickness(-14,-14,-14,10),Padding=new Thickness(14,10,14,6)}; internal readonly Slider TransparencySlider=new(){Minimum=0,Maximum=85,Width=150,TickFrequency=5,IsSnapToTickEnabled=false}; readonly TextBlock transparencyValue=new(){Width=36,VerticalAlignment=VerticalAlignment.Center}; Point dragStart; bool trackingHeader,draggedHeader,clickedTitle;
 internal BoxWindow(Program app,BoxConfig config){this.app=app;Config=config;Icon=AppIcons.WindowIcon;Title=config.Name;Width=Math.Max(300,config.Width);Height=Math.Max(220,config.Height);Left=config.X;Top=config.Y;MinWidth=300;MinHeight=220;WindowStyle=WindowStyle.None;ResizeMode=config.Locked?ResizeMode.NoResize:ResizeMode.CanResizeWithGrip;ShowInTaskbar=false;Background=new SolidColorBrush(Color.FromArgb(155,35,39,47));Foreground=Theme.Text;
 var root=new DockPanel{Margin=new Thickness(14)};Content=root;var header=new DockPanel();headerSurface.Child=header;DockPanel.SetDock(headerSurface,Dock.Top);root.Children.Add(headerSurface);var menuButton=Manager.Button("⋯",()=>ShowMenu());menuButton.ToolTip="盒子设置";menuButton.Width=32;menuButton.Height=30;menuButton.FontSize=22;menuButton.Padding=new Thickness(0);menuButton.Margin=new Thickness(8,0,0,0);menuButton.HorizontalContentAlignment=HorizontalAlignment.Center;menuButton.Background=Brushes.Transparent;menuButton.BorderThickness=new Thickness(0);DockPanel.SetDock(menuButton,Dock.Right);header.Children.Add(menuButton);nameEditor.Style=Theme.EditorStyle;nameEditor.Background=new SolidColorBrush(Color.FromArgb(25,255,255,255));nameEditor.MinWidth=120;nameEditor.MaxWidth=260;title.TextTrimming=TextTrimming.CharacterEllipsis;title.Text=config.Name;title.ToolTip="单击标题改名，按住拖动调整位置";title.VerticalAlignment=VerticalAlignment.Center;titleHost.Children.Add(title);titleHost.Children.Add(nameEditor);header.Children.Add(titleHost);headerSurface.PreviewMouseLeftButtonDown+=HeaderDown;headerSurface.PreviewMouseMove+=HeaderMove;headerSurface.PreviewMouseLeftButtonUp+=HeaderUp;nameEditor.KeyDown+=(_,e)=>{if(e.Key==Key.Enter){FinishRename(true);e.Handled=true;}else if(e.Key==Key.Escape){FinishRename(false);e.Handled=true;}};nameEditor.LostKeyboardFocus+=(_,_)=>FinishRename(true);
 var footer=new StackPanel();DockPanel.SetDock(footer,Dock.Bottom);root.Children.Add(footer);status.Foreground=Theme.Muted;status.Margin=new Thickness(0,8,0,4);footer.Children.Add(status);var appearance=new DockPanel();var transparencyLabel=new TextBlock{Text="透明度",Foreground=Theme.Muted,FontSize=11,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,8,0)};DockPanel.SetDock(transparencyLabel,Dock.Left);appearance.Children.Add(transparencyLabel);DockPanel.SetDock(transparencyValue,Dock.Right);appearance.Children.Add(transparencyValue);transparencyValue.Foreground=Theme.Muted;transparencyValue.FontSize=11;TransparencySlider.Style=Theme.SliderStyle;TransparencySlider.Width=double.NaN;TransparencySlider.ToolTip="调整背景透明度，文字和图标保持清晰";appearance.Children.Add(TransparencySlider);footer.Children.Add(appearance);TransparencySlider.Value=Math.Clamp(config.Transparency,0,85);ApplyTransparency();TransparencySlider.ValueChanged+=(_,_)=>{Config.Transparency=TransparencySlider.Value;ApplyTransparency();app.Save();};entries.Background=Brushes.Transparent;entries.Foreground=Theme.Text;entries.BorderThickness=new Thickness(0);entries.SelectionMode=SelectionMode.Extended;root.Children.Add(entries);AllowDrop=true;DragOver+=(_,e)=>{e.Effects=e.Data.GetDataPresent(DataFormats.FileDrop)?(Config.Folder==null?DragDropEffects.Link:DragDropEffects.Move):DragDropEffects.None;e.Handled=true;};Drop+=OnDrop;entries.MouseDoubleClick+=(_,_)=>{if(entries.SelectedItem is Entry item)Try(()=>Process.Start(new ProcessStartInfo(item.Path){UseShellExecute=true}));};entries.ContextMenu=new ContextMenu();Theme.Menu(entries.ContextMenu);entries.ContextMenu.Opened+=(_,_)=>FileMenu();
 SourceInitialized+=(_,_)=>Native.Glass(this);LocationChanged+=(_,_)=>SaveLayout();SizeChanged+=(_,_)=>{titleHost.MaxWidth=Math.Max(80,ActualWidth-90);SaveLayout();};Closing+=(_,e)=>{if(!closing){e.Cancel=true;Hide();}};timer.Tick+=(_,_)=>{Refresh();if(Config.Folder==null)foreach(var path in Config.Entries)try{DesktopIcons.EnsureHidden(path);}catch(Exception ex){status.Text="图标隐藏失效："+ex.Message;}};timer.Start();BindWatcher();Refresh();if(Config.Folder==null)foreach(var path in Config.Entries)Try(()=>DesktopIcons.Hide(path));}
  internal bool EditingName=>nameEditor.Visibility==Visibility.Visible;
 internal TextBox NameEditor=>nameEditor;
 internal Border HeaderSurface=>headerSurface;
 void ApplyTransparency(){var amount=Math.Clamp(TransparencySlider.Value,0,85);Background=new SolidColorBrush(Color.FromArgb((byte)Math.Round(255*(1-amount/100)),35,39,47));transparencyValue.Text=Math.Round(amount)+"%";}
 static bool InteractiveAncestor(DependencyObject? node){while(node!=null){if(node is System.Windows.Controls.Primitives.ButtonBase or TextBox or Slider)return true;node=VisualTreeHelper.GetParent(node);}return false;}
 void HeaderDown(object sender,MouseButtonEventArgs e){if(InteractiveAncestor(e.OriginalSource as DependencyObject))return;dragStart=e.GetPosition(this);trackingHeader=true;draggedHeader=false;clickedTitle=titleHost.IsMouseOver;Mouse.Capture(headerSurface);e.Handled=true;}
 void HeaderMove(object sender,MouseEventArgs e){if(!trackingHeader||Config.Locked||e.LeftButton!=MouseButtonState.Pressed)return;var p=e.GetPosition(this);if(Math.Abs(p.X-dragStart.X)<SystemParameters.MinimumHorizontalDragDistance&&Math.Abs(p.Y-dragStart.Y)<SystemParameters.MinimumVerticalDragDistance)return;draggedHeader=true;trackingHeader=false;Mouse.Capture(null);try{DragMove();}catch(InvalidOperationException){}e.Handled=true;}
 void HeaderUp(object sender,MouseButtonEventArgs e){if(!trackingHeader)return;trackingHeader=false;Mouse.Capture(null);if(!draggedHeader&&clickedTitle)BeginRename();e.Handled=true;}
 internal void BeginRename(){if(EditingName)return;nameEditor.Text=Config.Name;title.Visibility=Visibility.Collapsed;nameEditor.Visibility=Visibility.Visible;nameEditor.Focus();nameEditor.SelectAll();}
 internal void FinishRename(bool commit){if(!EditingName)return;var value=nameEditor.Text.Trim();nameEditor.Visibility=Visibility.Collapsed;title.Visibility=Visibility.Visible;if(commit&&!string.IsNullOrWhiteSpace(value)&&value!=Config.Name){Config.Name=value;Title=value;title.Text=value;app.Save();app.RefreshManager();}else title.Text=Config.Name;}
 void SaveLayout(){if(!IsLoaded)return;Config.X=Left;Config.Y=Top;Config.Width=ActualWidth;Config.Height=ActualHeight;app.Save();}
 void BindWatcher(){watcher?.Dispose();watcher=null;if(Config.Folder!=null&&Directory.Exists(Config.Folder)){try{watcher=new FileSystemWatcher(Config.Folder){NotifyFilter=NotifyFilters.FileName|NotifyFilters.DirectoryName|NotifyFilters.Size|NotifyFilters.LastWrite};watcher.Changed+=Changed;watcher.Created+=Changed;watcher.Deleted+=Changed;watcher.Renamed+=Changed;watcher.EnableRaisingEvents=true;}catch(Exception ex){status.Text=ex.Message;}}}
 void Changed(object s,FileSystemEventArgs e)=>Dispatcher.BeginInvoke(Refresh);
 internal void Refresh(){try{var selected=entries.SelectedItems.Cast<Entry>().Select(x=>x.Path).ToHashSet(StringComparer.OrdinalIgnoreCase);IEnumerable<string> paths=Config.Entries;if(Config.Folder!=null){if(!Directory.Exists(Config.Folder)){entries.ItemsSource=null;status.Text="映射路径失效，请通过 ⋯ 重新绑定。";return;}paths=Directory.EnumerateFileSystemEntries(Config.Folder);}var items=paths.OrderBy(p=>System.IO.Path.GetFileName(p),StringComparer.CurrentCultureIgnoreCase).Select(p=>new Entry{Path=p}).ToList();entries.ItemsSource=items;foreach(var item in items.Where(i=>selected.Contains(i.Path)))entries.SelectedItems.Add(item);SetView();status.Text=items.Count+" 个项目 · "+(Config.Folder==null?"普通盒子":"文件夹映射");}catch(Exception ex){status.Text="读取失败："+ex.Message;}}
 void SetView(){if(Config.View=="详细信息"){var view=new GridView();foreach(var c in new[]{("名称","Name",170d),("类型","Type",65d),("大小","Size",80d),("修改时间","Modified",125d)})view.Columns.Add(new GridViewColumn{Header=c.Item1,DisplayMemberBinding=new System.Windows.Data.Binding(c.Item2),Width=c.Item3});entries.View=view;entries.ItemsPanel=new ItemsPanelTemplate(new FrameworkElementFactory(typeof(VirtualizingStackPanel)));entries.ItemTemplate=null;}else{entries.View=null;var p=new FrameworkElementFactory(Config.View=="图标"?typeof(WrapPanel):typeof(VirtualizingStackPanel));entries.ItemsPanel=new ItemsPanelTemplate(p);var stack=new FrameworkElementFactory(typeof(StackPanel));stack.SetValue(FrameworkElement.WidthProperty,Config.View=="图标"?100d:250d);stack.SetValue(FrameworkElement.MarginProperty,new Thickness(4,8,4,8));if(Config.View=="图标"){var icon=new FrameworkElementFactory(typeof(System.Windows.Controls.Image));icon.SetBinding(System.Windows.Controls.Image.SourceProperty,new System.Windows.Data.Binding("Icon"));icon.SetValue(FrameworkElement.HeightProperty,32d);icon.SetValue(FrameworkElement.WidthProperty,32d);icon.SetValue(FrameworkElement.HorizontalAlignmentProperty,HorizontalAlignment.Center);stack.AppendChild(icon);}var text=new FrameworkElementFactory(typeof(TextBlock));text.SetBinding(TextBlock.TextProperty,new System.Windows.Data.Binding("Name"));text.SetValue(TextBlock.TextTrimmingProperty,TextTrimming.CharacterEllipsis);stack.AppendChild(text);entries.ItemTemplate=new DataTemplate{VisualTree=stack};}}
 void ShowMenu(){var m=new ContextMenu();Theme.Menu(m);Add(m,"改名",()=>Dispatcher.BeginInvoke(BeginRename));Add(m,Config.Locked?"解锁位置":"锁定位置",()=>{Config.Locked=!Config.Locked;ResizeMode=Config.Locked?ResizeMode.NoResize:ResizeMode.CanResizeWithGrip;app.Save();});foreach(var v in new[]{"图标","列表","详细信息"})Add(m,"视图 · "+v,()=>{Config.View=v;app.Save();Refresh();});if(Config.Folder!=null){Add(m,"重新绑定文件夹",()=>{var f=Manager.PickFolder();if(f==null)return;Config.Folder=f;BindWatcher();app.Save();Refresh();});Add(m,"打开映射文件夹",()=>Try(()=>Process.Start(new ProcessStartInfo(Config.Folder){UseShellExecute=true})));}Add(m,"删除盒子（保留文件）",()=>app.Delete(this));m.IsOpen=true;}
 static void Add(ContextMenu m,string text,Action action){var i=new MenuItem{Header=text};i.Click+=(_,_)=>action();m.Items.Add(i);}
 void FileMenu(){var m=entries.ContextMenu!;m.Items.Clear();if(entries.SelectedItem is not Entry item)return;Add(m,"打开",()=>Try(()=>Process.Start(new ProcessStartInfo(item.Path){UseShellExecute=true})));Add(m,"在资源管理器中显示",()=>Try(()=>Process.Start(new ProcessStartInfo("explorer.exe","/select,\""+item.Path+"\""){UseShellExecute=true})));if(Config.Folder==null)Add(m,"移出盒子（文件不移动）",()=>{foreach(var i in entries.SelectedItems.Cast<Entry>().ToArray()){try{DesktopIcons.Restore(i.Path);Config.Entries.Remove(i.Path);}catch(Exception ex){MessageBox.Show("恢复失败，入口保留："+ex.Message);}}app.Save();Refresh();});}
 void OnDrop(object s,DragEventArgs e){if(e.Data.GetData(DataFormats.FileDrop) is not string[] paths)return;var failures=new List<string>();foreach(var path in paths){try{if(Config.Folder==null){if(!File.Exists(path)&&!Directory.Exists(path))throw new IOException("文件不存在");if(!Config.Entries.Contains(path,StringComparer.OrdinalIgnoreCase)){if(app.Windows.Any(w=>w!=this&&w.Config.Entries.Contains(path,StringComparer.OrdinalIgnoreCase)))throw new IOException("该入口已在其他普通盒子中，请先移出。");DesktopIcons.Hide(path);Config.Entries.Add(path);}}else FileActions.MoveInto(path,Config.Folder);}catch(Exception ex){failures.Add(System.IO.Path.GetFileName(path)+"："+ex.Message);}}app.Save();Refresh();if(failures.Count>0)MessageBox.Show(string.Join("\n",failures),"部分项目未收纳");e.Handled=true;}
 void Try(Action action){try{action();}catch(Exception ex){MessageBox.Show(ex.Message,"操作失败");}}
 internal void DisposeAndClose(){closing=true;watcher?.Dispose();timer.Stop();if(Config.Folder==null)foreach(var p in Config.Entries)try{DesktopIcons.Restore(p);}catch(Exception ex){MessageBox.Show("图标恢复失败，恢复记录已保留："+ex.Message);}Close();}
}









