using System.IO;
using System.Runtime.InteropServices;
using System.Text.Json;
namespace DesktopBox;
internal static class DesktopIcons {
 [StructLayout(LayoutKind.Sequential)] internal struct Point {public int X;public int Y;}
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetPtr(IntPtr self,out IntPtr result);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetCount(IntPtr self,uint flags,out int count);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetItem(IntPtr self,int index,out IntPtr item);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetPosition(IntPtr self,IntPtr item,out Point point);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int Position(IntPtr self,uint count,[MarshalAs(UnmanagedType.LPArray,SizeParamIndex=1)]IntPtr[] items,[MarshalAs(UnmanagedType.LPArray,SizeParamIndex=1)]Point[] points,uint flags);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetFolder(IntPtr self,ref Guid iid,out IntPtr folder);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int Name(IntPtr self,uint mode,out IntPtr text);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int AutoArrange(IntPtr self);
 [ComImport,Guid("6D5140C1-7436-11CE-8034-00AA006009FA"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface ServiceProvider {[PreserveSig]int QueryService(ref Guid service,ref Guid iid,out IntPtr obj);}
 [DllImport("shell32.dll")] static extern int SHCreateItemWithParent(IntPtr parent,IntPtr folder,IntPtr child,ref Guid iid,out IntPtr item);
 static T Method<T>(IntPtr ptr,int slot) where T:Delegate=>Marshal.GetDelegateForFunctionPointer<T>(Marshal.ReadIntPtr(Marshal.ReadIntPtr(ptr),slot*IntPtr.Size));
 static readonly string Journal=Path.Combine(Path.GetDirectoryName(Store.PathName)!,"icon-recovery.json");
 static Dictionary<string,Point> saved=new(StringComparer.OrdinalIgnoreCase);
 static void Persist(){Directory.CreateDirectory(Path.GetDirectoryName(Journal)!);var tmp=Journal+".tmp";File.WriteAllText(tmp,JsonSerializer.Serialize(saved,new JsonSerializerOptions{IncludeFields=true}));File.Move(tmp,Journal,true);}
 static IntPtr View(){dynamic windows=Activator.CreateInstance(Type.GetTypeFromCLSID(new Guid("9BA05972-F6A8-11CF-A442-00A0C90A8F39"))!)!;object location=0,root=0;int hwnd;object desktop=windows.FindWindowSW(ref location,ref root,8,out hwnd,1);try{var service=(ServiceProvider)desktop;var sid=new Guid("4C96BE40-915C-11CF-99D3-00AA004AE837");var browserId=new Guid("000214E2-0000-0000-C000-000000000046");Marshal.ThrowExceptionForHR(service.QueryService(ref sid,ref browserId,out var browser));try{Marshal.ThrowExceptionForHR(Method<GetPtr>(browser,15)(browser,out var shellView));try{var iid=new Guid("CDE725B0-CCC9-4519-917E-325D72FAB4CE");Marshal.ThrowExceptionForHR(Marshal.QueryInterface(shellView,in iid,out var view));return view;}finally{Marshal.Release(shellView);}}finally{Marshal.Release(browser);}}finally{Marshal.ReleaseComObject(desktop);Marshal.ReleaseComObject(windows);}}
 static void WithItem(string path,Action<IntPtr,IntPtr> action){var view=View();try{var folderId=new Guid("000214E6-0000-0000-C000-000000000046");Marshal.ThrowExceptionForHR(Method<GetFolder>(view,5)(view,ref folderId,out var folder));try{Marshal.ThrowExceptionForHR(Method<GetCount>(view,7)(view,2,out var count));for(int i=0;i<count;i++){Marshal.ThrowExceptionForHR(Method<GetItem>(view,6)(view,i,out var child));try{var iid=new Guid("43826D1E-E718-42EE-BC55-A1E261C37BFE");if(SHCreateItemWithParent(IntPtr.Zero,folder,child,ref iid,out var item)<0)continue;try{var name=ShellItems.Identity(item);if(string.Equals(name,path,StringComparison.OrdinalIgnoreCase)){action(view,child);return;}}finally{Marshal.Release(item);}}finally{Marshal.FreeCoTaskMem(child);}}throw new IOException("未找到对应的桌面图标，未改变文件。");}finally{Marshal.Release(folder);}}finally{Marshal.Release(view);}}
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetMetrics(IntPtr self,out uint mode,out int size);
 internal static int IconSize(){var view=View();try{var iid=new Guid("1AF3A467-214F-4298-908E-06B03E0B39F9");Marshal.ThrowExceptionForHR(Marshal.QueryInterface(view,in iid,out var extended));try{Marshal.ThrowExceptionForHR(Method<GetMetrics>(extended,36)(extended,out _,out var size));return Math.Clamp(size,16,256);}finally{Marshal.Release(extended);}}finally{Marshal.Release(view);}}
 internal sealed record DesktopItem(string Id,string Name,Point Position);
 internal static IReadOnlyList<DesktopItem> ReadAll(){var result=new List<DesktopItem>();var view=View();try{var folderId=new Guid("000214E6-0000-0000-C000-000000000046");Marshal.ThrowExceptionForHR(Method<GetFolder>(view,5)(view,ref folderId,out var folder));try{Marshal.ThrowExceptionForHR(Method<GetCount>(view,7)(view,2,out var count));for(int i=0;i<count;i++){Marshal.ThrowExceptionForHR(Method<GetItem>(view,6)(view,i,out var child));try{var iid=new Guid("43826D1E-E718-42EE-BC55-A1E261C37BFE");if(SHCreateItemWithParent(IntPtr.Zero,folder,child,ref iid,out var item)<0)continue;try{var id=ShellItems.Identity(item);if(id.Length==0)continue;Marshal.ThrowExceptionForHR(Method<GetPosition>(view,11)(view,child,out var position));result.Add(new DesktopItem(id,ShellItems.NameOf(item,0),position));}finally{Marshal.Release(item);}}finally{Marshal.FreeCoTaskMem(child);}}}finally{Marshal.Release(folder);}}finally{Marshal.Release(view);}return result;}
 internal static Point Inspect(string path){Point p=default;WithItem(path,(v,i)=>Marshal.ThrowExceptionForHR(Method<GetPosition>(v,11)(v,i,out p)));return p;}
 internal static void Restore(string path){if(!saved.TryGetValue(path,out var original))return;if(!ShellItems.Exists(path)){saved.Remove(path);Persist();return;}WithItem(path,(v,i)=>{Marshal.ThrowExceptionForHR(Method<Position>(v,16)(v,1,[i],[original],0x80));Marshal.ThrowExceptionForHR(Method<GetPosition>(v,11)(v,i,out var actual));if(actual.X!=original.X||actual.Y!=original.Y)throw new IOException("图标未恢复到原位置，恢复记录已保留。");});saved.Remove(path);Persist();}
 internal static void Recover(){if(File.Exists(Journal))saved=JsonSerializer.Deserialize<Dictionary<string,Point>>(File.ReadAllText(Journal),new JsonSerializerOptions{IncludeFields=true})??new();foreach(var path in saved.Keys.ToArray()){if(!ShellItems.Exists(path)){saved.Remove(path);Persist();}else Restore(path);}}
}
