using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Media;
namespace DesktopBox;
internal sealed class DesktopLayer:IDisposable {
 const string RepositionFormat="DesktopBox.DesktopIconPosition";
 [StructLayout(LayoutKind.Sequential)]struct Rect{public int Left,Top,Right,Bottom;}
 readonly record struct ScreenRect(int Left,int Top,int Right,int Bottom){internal bool Intersects(ScreenRect other)=>Left<other.Right&&Right>other.Left&&Top<other.Bottom&&Bottom>other.Top;}
 delegate bool VisitWindow(IntPtr window,IntPtr param);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern IntPtr FindWindowEx(IntPtr parent,IntPtr after,string kind,string? title);
 [DllImport("user32.dll")]static extern bool EnumWindows(VisitWindow visit,IntPtr param);
 [DllImport("user32.dll")]static extern bool ShowWindow(IntPtr window,int command);
 [DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr window);
 [DllImport("user32.dll")]static extern bool IsWindow(IntPtr window);
 [DllImport("user32.dll")]static extern bool GetCursorPos(out DesktopIcons.Point point);
 [DllImport("user32.dll")]static extern bool ScreenToClient(IntPtr window,ref DesktopIcons.Point point);
 [DllImport("user32.dll")]static extern IntPtr WindowFromPoint(DesktopIcons.Point point);
 [DllImport("user32.dll")]static extern bool IsChild(IntPtr parent,IntPtr child);
 [DllImport("user32.dll",CharSet=CharSet.Unicode)]static extern int GetClassName(IntPtr window,StringBuilder text,int count);
 [DllImport("user32.dll")]static extern IntPtr GetParent(IntPtr window);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr window,out Rect rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr window,ref DesktopIcons.Point point);
 [DllImport("user32.dll")]static extern bool GetWindowRect(IntPtr window,out Rect rect);
 [DllImport("user32.dll",SetLastError=true)]static extern IntPtr SetParent(IntPtr child,IntPtr parent);
 [DllImport("user32.dll")]static extern int GetWindowLong(IntPtr window,int index);
 [DllImport("user32.dll")]static extern int SetWindowLong(IntPtr window,int index,int value);
 [DllImport("user32.dll")]static extern bool SetWindowPos(IntPtr window,IntPtr after,int x,int y,int width,int height,uint flags);
 static string Marker=>Path.Combine(Path.GetDirectoryName(Store.PathName)!,"desktop-layer-recovery.json");
 internal sealed record Recovery(long Handle);
 static string Class(IntPtr window){var text=new StringBuilder(128);GetClassName(window,text,text.Capacity);return text.ToString();}
 static IntPtr FindList(){IntPtr list=IntPtr.Zero;EnumWindows((window,_)=>{var view=FindWindowEx(window,IntPtr.Zero,"SHELLDLL_DefView",null);if(view==IntPtr.Zero)return true;list=FindWindowEx(view,IntPtr.Zero,"SysListView32",null);return list==IntPtr.Zero;},IntPtr.Zero);return list;}
 internal static bool NativeVisible {get{var list=FindList();return list!=IntPtr.Zero&&IsWindowVisible(list);}}
 internal static void RestoreNative(){if(!File.Exists(Marker))return;var record=JsonSerializer.Deserialize<Recovery>(File.ReadAllText(Marker))??throw new IOException("桌面恢复记录无效");var list=new IntPtr(record.Handle);if(!IsWindow(list)||Class(list)!="SysListView32"||Class(GetParent(list))!="SHELLDLL_DefView")list=FindList();if(list==IntPtr.Zero)throw new IOException("Explorer 桌面暂不可用，恢复记录已保留");ShowWindow(list,8);if(!IsWindowVisible(list))throw new IOException("系统桌面尚未恢复，恢复记录已保留");File.Delete(Marker);}
 readonly Func<Settings> settings;readonly Func<IEnumerable<BoxWindow>> boxes;Window? window;readonly Canvas icons=new();readonly HashSet<string> selected=new(StringComparer.OrdinalIgnoreCase);IntPtr listHandle;string layoutKey="";bool disposed;Point dragOffset;string? selectionAnchor;
 internal DesktopLayer(Func<Settings> settings,Func<IEnumerable<BoxWindow>> boxes){this.settings=settings;this.boxes=boxes;icons.Background=Brushes.Transparent;icons.AllowDrop=true;icons.Focusable=true;icons.PreviewKeyDown+=DesktopKeyDown;icons.MouseLeftButtonDown+=(_,e)=>{if(ReferenceEquals(e.OriginalSource,icons)){selected.Clear();selectionAnchor=null;UpdateSelectionVisuals();icons.Focus();}};icons.DragOver+=(_,e)=>{if(!e.Data.GetDataPresent(RepositionFormat))return;e.Effects=DragDropEffects.Move;e.Handled=true;};icons.Drop+=RepositionDrop;}
 internal int DisplayedCount=>icons.Children.Count;
 internal bool Contains(string id)=>icons.Children.OfType<FrameworkElement>().Any(x=>string.Equals(x.Tag as string,id,StringComparison.OrdinalIgnoreCase));
 internal double RenderedIconPixels=>icons.Children.OfType<Border>().Select(x=>((StackPanel)x.Child).Children.OfType<Image>().First().Width*(window==null?1:VisualTreeHelper.GetDpi(window).DpiScaleX)).FirstOrDefault();
 internal bool Attached=>window!=null&&GetParent(new WindowInteropHelper(window).Handle)==GetParent(listHandle);
 internal void Refresh(){if(disposed)return;var visibleBoxes=boxes().Where(x=>x.IsVisible).ToArray();if(visibleBoxes.Length==0){Stop();return;}var collected=settings().Boxes.Where(x=>x.Folder==null).SelectMany(x=>x.Entries).ToHashSet(StringComparer.OrdinalIgnoreCase);var items=DesktopIcons.ReadAll();var native=FindList();if(native==IntPtr.Zero){Stop();if(collected.Count>0)throw new IOException("Explorer 桌面暂不可用");return;}if(window!=null&&native!=listHandle){window.Close();window=null;layoutKey="";listHandle=IntPtr.Zero;}if(window==null&&!IsWindowVisible(native)&&!File.Exists(Marker))return;GetClientRect(native,out var desktopRect);ReserveSlots(native,desktopRect,items,collected,visibleBoxes);if(collected.Count==0||!items.Any(x=>collected.Contains(x.Id))){Stop();return;}
  if(window==null){if(!IsWindowVisible(native)&&!File.Exists(Marker))return;listHandle=native;Directory.CreateDirectory(Path.GetDirectoryName(Marker)!);var temp=Marker+".tmp";File.WriteAllText(temp,JsonSerializer.Serialize(new Recovery(listHandle.ToInt64())));File.Move(temp,Marker,true);window=new Window{Title="桌面盒子 · 桌面图标层",WindowStyle=WindowStyle.None,ResizeMode=ResizeMode.NoResize,AllowsTransparency=true,Background=Brushes.Transparent,ShowInTaskbar=false,ShowActivated=false,Content=icons,Left=0,Top=0};window.SourceInitialized+=(_,_)=>{var handle=new WindowInteropHelper(window).Handle;var style=GetWindowLong(handle,-16);SetWindowLong(handle,-16,(style&~unchecked((int)0x80000000))|0x40000000);SetParent(handle,GetParent(listHandle));if(GetParent(handle)!=GetParent(listHandle))throw new IOException("系统拒绝桌面图标层嵌入");HwndSource.FromHwnd(handle).AddHook((IntPtr h,int msg,IntPtr w,IntPtr l,ref bool handled)=>{if(msg==0x21){handled=true;return new IntPtr(3);}return IntPtr.Zero;});};try{window.Show();}catch{Stop();throw;}}
  GetClientRect(listHandle,out var rect);var dpi=VisualTreeHelper.GetDpi(window);window.Width=Math.Max(1,(rect.Right-rect.Left)/dpi.DpiScaleX);window.Height=Math.Max(1,(rect.Bottom-rect.Top)/dpi.DpiScaleY);SetWindowPos(new WindowInteropHelper(window).Handle,IntPtr.Zero,0,0,rect.Right-rect.Left,rect.Bottom-rect.Top,0x54);
  var size=DesktopIcons.IconSize();var visible=items.Where(x=>!collected.Contains(x.Id)).ToArray();selected.IntersectWith(visible.Select(x=>x.Id));var key=$"{size}:{dpi.DpiScaleX}|"+string.Join("|",visible.Select(x=>$"{x.Id}:{x.Position.X},{x.Position.Y}"));if(key!=layoutKey){icons.Children.Clear();foreach(var item in visible)Add(item,dpi,size);layoutKey=key;UpdateSelectionVisuals();}ShowWindow(listHandle,0);if(IsWindowVisible(listHandle)){Stop();throw new IOException("系统不允许隐藏原桌面图标层");}
 }
 void SelectTile(string id,ModifierKeys modifiers){var ordered=icons.Children.OfType<Border>().Select(tile=>tile.Tag as string).Where(path=>path!=null).Cast<string>().ToArray();var index=Array.IndexOf(ordered,id);if((modifiers&ModifierKeys.Shift)!=0&&selectionAnchor!=null){var anchor=Array.IndexOf(ordered,selectionAnchor);if(anchor<0)anchor=index;if((modifiers&ModifierKeys.Control)==0)selected.Clear();for(var i=Math.Min(anchor,index);i<=Math.Max(anchor,index);i++)selected.Add(ordered[i]);}else if((modifiers&ModifierKeys.Control)!=0){if(!selected.Add(id))selected.Remove(id);selectionAnchor=id;}else{if(!selected.Contains(id)){selected.Clear();selected.Add(id);}selectionAnchor=id;}UpdateSelectionVisuals();}
 void UpdateSelectionVisuals(){foreach(var tile in icons.Children.OfType<Border>()){var isSelected=tile.Tag is string id&&selected.Contains(id);tile.BorderThickness=new Thickness(1);tile.BorderBrush=isSelected?new SolidColorBrush(Color.FromArgb(180,165,210,255)):Brushes.Transparent;tile.Background=isSelected?new SolidColorBrush(Color.FromArgb(55,110,170,235)):Brushes.Transparent;}}
 void DesktopKeyDown(object sender,KeyEventArgs e){if((Keyboard.Modifiers&ModifierKeys.Control)==0)return;if(e.Key==Key.A){selected.Clear();foreach(var tile in icons.Children.OfType<Border>())if(tile.Tag is string id)selected.Add(id);UpdateSelectionVisuals();e.Handled=true;}else if(e.Key==Key.C){var paths=icons.Children.OfType<Border>().Select(tile=>tile.Tag as string).Where(id=>id!=null&&selected.Contains(id!)).Cast<string>().ToArray();if(paths.Length>0)try{Clipboard.SetDataObject(ShellItems.CreateData(paths),true);}catch(Exception ex){MessageBox.Show("复制失败："+ex.Message);}e.Handled=true;}else if(e.Key==Key.V){PasteToDesktop();e.Handled=true;}}
 void PasteToDesktop(){try{var data=Clipboard.GetDataObject();if(data==null)return;var paths=ShellItems.Read(data).Where(path=>!ShellItems.IsVirtual(path)&& (File.Exists(path)||Directory.Exists(path))).ToArray();if(paths.Length==0)return;var desktop=Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);foreach(var source in paths){var destination=UniqueDesktopPath(desktop,Path.GetFileName(source));if(File.Exists(source))File.Copy(source,destination);else CopyDirectory(source,destination);}layoutKey="";Refresh();}catch(Exception ex){MessageBox.Show("粘贴失败："+ex.Message);}}
 static string UniqueDesktopPath(string directory,string name){var candidate=Path.Combine(directory,name);if(!File.Exists(candidate)&&!Directory.Exists(candidate))return candidate;var stem=Path.GetFileNameWithoutExtension(name);var extension=Path.GetExtension(name);for(var i=1;i<int.MaxValue;i++){candidate=Path.Combine(directory,$"{stem} - 副本{i}{extension}");if(!File.Exists(candidate)&&!Directory.Exists(candidate))return candidate;}throw new IOException("无法为粘贴文件分配名称。");}
 static void CopyDirectory(string source,string destination){Directory.CreateDirectory(destination);foreach(var file in Directory.EnumerateFiles(source))File.Copy(file,Path.Combine(destination,Path.GetFileName(file)));foreach(var directory in Directory.EnumerateDirectories(source))CopyDirectory(directory,Path.Combine(destination,Path.GetFileName(directory)));}
 void ReserveSlots(IntPtr native,Rect desktopRect,IReadOnlyList<DesktopIcons.DesktopItem> items,HashSet<string> collected,IReadOnlyList<BoxWindow> visibleBoxes){if(desktopRect.Right<=desktopRect.Left||desktopRect.Bottom<=desktopRect.Top)return;var origin=new DesktopIcons.Point();if(!ClientToScreen(native,ref origin))return;var spacing=DesktopIcons.Spacing();if(spacing.X<=0||spacing.Y<=0)return;var obstacles=new List<ScreenRect>();foreach(var box in visibleBoxes){if(!GetWindowRect(new WindowInteropHelper(box).Handle,out var bounds))continue;obstacles.Add(new ScreenRect(bounds.Left,bounds.Top,bounds.Right,bounds.Bottom));}if(obstacles.Count==0)return;ScreenRect Cell(DesktopIcons.Point point)=>new(origin.X+point.X,origin.Y+point.Y,origin.X+point.X+spacing.X,origin.Y+point.Y+spacing.Y);var occupied=items.Where(x=>!collected.Contains(x.Id)).Select(x=>Cell(x.Position)).ToList();foreach(var item in items.Where(x=>!collected.Contains(x.Id))){var current=Cell(item.Position);if(!obstacles.Any(current.Intersects))continue;occupied.Remove(current);var target=NearestFree(item.Position,desktopRect,spacing,origin,occupied,obstacles);if(target is null){occupied.Add(current);continue;}try{DesktopIcons.Move(item.Id,target.Value);occupied.Add(Cell(target.Value));}catch(IOException){occupied.Add(current);}catch(COMException){occupied.Add(current);}}
 }
 bool TryGetDesktopDropPosition(Point dragPoint,out DesktopIcons.Point target){target=default;if(window==null||listHandle==IntPtr.Zero||!GetCursorPos(out var screen))return false;var under=WindowFromPoint(screen);var defView=GetParent(listHandle);var overlay=new WindowInteropHelper(window).Handle;var targetClass=Class(under);bool desktopTarget=under==defView||under==listHandle||IsChild(defView,under)||under==overlay||IsChild(overlay,under)||targetClass is "Progman" or "WorkerW" or "SHELLDLL_DefView" or "SysListView32";if(!desktopTarget)return false;if(!ScreenToClient(listHandle,ref screen)||!GetClientRect(listHandle,out var rect)||screen.X<0||screen.Y<0||screen.X>=rect.Right||screen.Y>=rect.Bottom)return false;var dpi=VisualTreeHelper.GetDpi(window);var spacing=DesktopIcons.Spacing();if(spacing.X<=0||spacing.Y<=0)return false;target=new DesktopIcons.Point{X=Math.Max(0,(int)Math.Round((screen.X-dragPoint.X*dpi.DpiScaleX)/spacing.X)*spacing.X),Y=Math.Max(0,(int)Math.Round((screen.Y-dragPoint.Y*dpi.DpiScaleY)/spacing.Y)*spacing.Y)};return true;}
 void MoveDesktopItems(IReadOnlyList<string> ids,string anchorId,DesktopIcons.Point desired){try{var native=FindList();if(native==IntPtr.Zero||!GetClientRect(native,out var rect))return;var spacing=DesktopIcons.Spacing();var origin=new DesktopIcons.Point();if(!ClientToScreen(native,ref origin))return;var all=DesktopIcons.ReadAll();var moving=all.Where(item=>ids.Contains(item.Id,StringComparer.OrdinalIgnoreCase)).ToArray();var anchor=moving.FirstOrDefault(item=>string.Equals(item.Id,anchorId,StringComparison.OrdinalIgnoreCase));if(anchor==null)return;var movingIds=moving.Select(item=>item.Id).ToHashSet(StringComparer.OrdinalIgnoreCase);var occupied=all.Where(item=>!movingIds.Contains(item.Id)).Select(item=>new ScreenRect(origin.X+item.Position.X,origin.Y+item.Position.Y,origin.X+item.Position.X+spacing.X,origin.Y+item.Position.Y+spacing.Y)).ToList();var obstacles=new List<ScreenRect>();foreach(var box in boxes().Where(box=>box.IsVisible)){if(GetWindowRect(new WindowInteropHelper(box).Handle,out var bounds))obstacles.Add(new ScreenRect(bounds.Left,bounds.Top,bounds.Right,bounds.Bottom));}foreach(var item in moving){var candidate=new DesktopIcons.Point{X=desired.X+item.Position.X-anchor.Position.X,Y=desired.Y+item.Position.Y-anchor.Position.Y};var target=NearestFree(candidate,rect,spacing,origin,occupied,obstacles);if(!target.HasValue)continue;DesktopIcons.Move(item.Id,target.Value);occupied.Add(new ScreenRect(origin.X+target.Value.X,origin.Y+target.Value.Y,origin.X+target.Value.X+spacing.X,origin.Y+target.Value.Y+spacing.Y));}layoutKey="";Refresh();}catch(IOException){}catch(COMException){}catch(InvalidOperationException){}}
 void RepositionDrop(object sender,DragEventArgs e){if(!e.Data.GetDataPresent(RepositionFormat))return;var ids=e.Data.GetData(RepositionFormat) switch{string[] multiple=>multiple,string single=>[single],_=>[]};if(ids.Length==0)return;var point=e.GetPosition(icons);var dpi=VisualTreeHelper.GetDpi(window!);var spacing=DesktopIcons.Spacing();var desired=new DesktopIcons.Point{X=Math.Max(0,(int)Math.Round((point.X-dragOffset.X)*dpi.DpiScaleX/spacing.X)*spacing.X),Y=Math.Max(0,(int)Math.Round((point.Y-dragOffset.Y)*dpi.DpiScaleY/spacing.Y)*spacing.Y)};MoveDesktopItems(ids,ids[0],desired);e.Effects=DragDropEffects.Move;e.Handled=true;}
 static DesktopIcons.Point? NearestFree(DesktopIcons.Point current,Rect desktopRect,DesktopIcons.Point spacing,DesktopIcons.Point origin,IReadOnlyList<ScreenRect> occupied,IReadOnlyList<ScreenRect> obstacles){var width=desktopRect.Right-desktopRect.Left;var height=desktopRect.Bottom-desktopRect.Top;double best=double.MaxValue;DesktopIcons.Point? result=null;for(int y=0;y+spacing.Y<=height;y+=spacing.Y)for(int x=0;x+spacing.X<=width;x+=spacing.X){var candidate=new DesktopIcons.Point{X=x,Y=y};var rect=new ScreenRect(origin.X+x,origin.Y+y,origin.X+x+spacing.X,origin.Y+y+spacing.Y);if(obstacles.Any(rect.Intersects)||occupied.Any(rect.Intersects))continue;var dx=(double)x-current.X;var dy=(double)y-current.Y;var distance=dx*dx+dy*dy;if(distance<best){best=distance;result=candidate;}}return result;}
 void Add(DesktopIcons.DesktopItem item,DpiScale dpi,int size){
  var panel=new StackPanel{Width=Math.Max(86,(size+20)/dpi.DpiScaleX),Margin=new Thickness(0,4,0,0)};
  panel.Children.Add(new Image{Source=ShellIcons.Get(item.Id,size),Width=size/dpi.DpiScaleX,Height=size/dpi.DpiScaleY,Margin=new Thickness(0,0,0,5)});
  panel.Children.Add(new TextBlock{Text=item.Name,Foreground=Brushes.White,FontSize=12,TextAlignment=TextAlignment.Center,TextWrapping=TextWrapping.Wrap,MaxHeight=34,TextTrimming=TextTrimming.CharacterEllipsis,Effect=new System.Windows.Media.Effects.DropShadowEffect{BlurRadius=3,ShadowDepth=1,Opacity=0.9}});
  var tile=new Border{Child=panel,Background=Brushes.Transparent,CornerRadius=new CornerRadius(4),Tag=item.Id,ToolTip=item.Name};
  Canvas.SetLeft(tile,item.Position.X/dpi.DpiScaleX);Canvas.SetTop(tile,item.Position.Y/dpi.DpiScaleY);
  Point origin=default;bool armed=false,internalDrag=false;string[] dragPaths=[];Dictionary<string,DesktopIcons.Point> originalPositions=[];
  tile.MouseLeftButtonDown+=(_,e)=>{icons.Focus();Keyboard.Focus(icons);SelectTile(item.Id,Keyboard.Modifiers);armed=e.ClickCount==1;origin=e.GetPosition(tile);if(armed)tile.CaptureMouse();if(e.ClickCount==2){Open(item.Id);e.Handled=true;}};
  tile.MouseLeftButtonUp+=(_,_)=>{DesktopIcons.Point? destination=null;if(internalDrag&&TryGetDesktopDropPosition(origin,out var drop))destination=drop;internalDrag=false;armed=false;tile.ReleaseMouseCapture();if(destination.HasValue)MoveDesktopItems(dragPaths,item.Id,destination.Value);else if(originalPositions.Count>0)RestoreDesktopPreview(dragPaths,originalPositions,dpi);};
  tile.LostMouseCapture+=(_,_)=>{armed=false;if(internalDrag){internalDrag=false;RestoreDesktopPreview(dragPaths,originalPositions,dpi);}};
  tile.MouseMove+=(_,e)=>{
   if(e.LeftButton!=MouseButtonState.Pressed)return;
   if(armed&&(Math.Abs(e.GetPosition(tile).X-origin.X)>=SystemParameters.MinimumHorizontalDragDistance||Math.Abs(e.GetPosition(tile).Y-origin.Y)>=SystemParameters.MinimumVerticalDragDistance)){
    armed=false;internalDrag=true;dragPaths=selected.Contains(item.Id)?icons.Children.OfType<Border>().Select(x=>x.Tag as string).Where(x=>x!=null&&selected.Contains(x!)).Cast<string>().ToArray():[item.Id];
    originalPositions=DesktopIcons.ReadAll().Where(x=>dragPaths.Contains(x.Id,StringComparer.OrdinalIgnoreCase)).ToDictionary(x=>x.Id,x=>x.Position,StringComparer.OrdinalIgnoreCase);
   }
   if(!internalDrag)return;
   if(TryGetDesktopDropPosition(origin,out var desired)){PreviewDesktopItems(dragPaths,item.Id,desired,originalPositions,dpi);return;}
   internalDrag=false;RestoreDesktopPreview(dragPaths,originalPositions,dpi);tile.ReleaseMouseCapture();
   if(!TryDragData(dragPaths,out var data)){layoutKey="";return;}data!.SetData(RepositionFormat,dragPaths);
   DesktopIcons.Point? desktopPosition=null;QueryContinueDragEventHandler query=(_,drag)=>{if((drag.KeyStates&DragDropKeyStates.LeftMouseButton)==0&&TryGetDesktopDropPosition(origin,out var destination)){desktopPosition=destination;drag.Action=DragAction.Cancel;}};tile.QueryContinueDrag+=query;try{DragDrop.DoDragDrop(tile,data,DragDropEffects.Link|DragDropEffects.Copy|DragDropEffects.Move);if(desktopPosition.HasValue)MoveDesktopItems(dragPaths,item.Id,desktopPosition.Value);}catch(System.Runtime.InteropServices.COMException){layoutKey="";}catch(InvalidOperationException){layoutKey="";}finally{tile.QueryContinueDrag-=query;}
  };
  tile.MouseEnter+=(_,_)=>{if(!selected.Contains(item.Id))tile.Background=new SolidColorBrush(Color.FromArgb(25,255,255,255));};
  tile.MouseLeave+=(_,_)=>UpdateSelectionVisuals();
  tile.PreviewMouseRightButtonUp+=(_,e)=>{e.Handled=true;DesktopShellMenu.Show(item.Id,new WindowInteropHelper(window!).Handle);};
  icons.Children.Add(tile);
 }
 void PreviewDesktopItems(IReadOnlyList<string> ids,string anchorId,DesktopIcons.Point desired,IReadOnlyDictionary<string,DesktopIcons.Point> originals,DpiScale dpi){if(!originals.TryGetValue(anchorId,out var anchor))return;foreach(var id in ids){if(!originals.TryGetValue(id,out var old))continue;var tile=icons.Children.OfType<Border>().FirstOrDefault(x=>string.Equals(x.Tag as string,id,StringComparison.OrdinalIgnoreCase));if(tile==null)continue;Canvas.SetLeft(tile,(desired.X+old.X-anchor.X)/dpi.DpiScaleX);Canvas.SetTop(tile,(desired.Y+old.Y-anchor.Y)/dpi.DpiScaleY);}}
 void RestoreDesktopPreview(IReadOnlyList<string> ids,IReadOnlyDictionary<string,DesktopIcons.Point> originals,DpiScale dpi){foreach(var id in ids){if(!originals.TryGetValue(id,out var point))continue;var tile=icons.Children.OfType<Border>().FirstOrDefault(x=>string.Equals(x.Tag as string,id,StringComparison.OrdinalIgnoreCase));if(tile==null)continue;Canvas.SetLeft(tile,point.X/dpi.DpiScaleX);Canvas.SetTop(tile,point.Y/dpi.DpiScaleY);}} internal static bool TryDragData(string id,out DataObject? data)=>TryDragData([id],out data); internal static bool TryDragData(IReadOnlyList<string> ids,out DataObject? data){data=null;try{if(ids.Count==0||ids.Any(id=>!ShellItems.Exists(id)))return false;data=ShellItems.CreateData(ids);return true;}catch(IOException){return false;}catch(COMException){return false;}catch(ArgumentException){return false;}}
 static void Open(string id){try{if(ShellItems.IsVirtual(id))System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("explorer.exe",id.StartsWith("shell:",StringComparison.OrdinalIgnoreCase)?id:"shell:"+id){UseShellExecute=true});else System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(id){UseShellExecute=true});}catch(Exception ex){MessageBox.Show(ex.Message,"无法打开入口");}}
 void Stop(){window?.Close();window=null;icons.Children.Clear();layoutKey="";RestoreNative();listHandle=IntPtr.Zero;}
 public void Dispose(){if(disposed)return;Stop();disposed=true;}
}
