using System.IO;
using System.Runtime.InteropServices;
using System.Text.Json;
namespace DesktopBox;
internal static class DesktopIcons {
 [StructLayout(LayoutKind.Sequential)] internal struct Point {public int X;public int Y;}
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetPtr(IntPtr self,out IntPtr result);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetCount(IntPtr self,uint flags,out int count);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetItem(IntPtr self,int index,out IntPtr item);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetPosition(IntPtr self,IntPtr item,out Point point);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int Position(IntPtr self,uint count,[MarshalAs(UnmanagedType.LPArray,SizeParamIndex=1)]IntPtr[] items,[MarshalAs(UnmanagedType.LPArray,SizeParamIndex=1)]Point[] points,uint flags);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int GetFolder(IntPtr self,ref Guid iid,out IntPtr folder);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int Name(IntPtr self,uint mode,out IntPtr text);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)] delegate int AutoArrange(IntPtr self);
 [ComImport,Guid("6D5140C1-7436-11CE-8034-00AA006009FA"),InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface ServiceProvider {[PreserveSig]int QueryService(ref Guid service,ref Guid iid,out IntPtr obj);}
 [DllImport("shell32.dll")] static extern int SHCreateItemWithParent(IntPtr parent,IntPtr folder,IntPtr child,ref Guid iid,out IntPtr item);
 static T Method<T>(IntPtr ptr,int slot) where T:Delegate=>Marshal.GetDelegateForFunctionPointer<T>(Marshal.ReadIntPtr(Marshal.ReadIntPtr(ptr),slot*IntPtr.Size));
 static readonly string Journal=Path.Combine(Path.GetDirectoryName(Store.PathName)!,"icon-recovery.json");
 static Dictionary<string,Point> saved=new(StringComparer.OrdinalIgnoreCase);
 static void Persist(){Directory.CreateDirectory(Path.GetDirectoryName(Journal)!);var tmp=Journal+".tmp";File.WriteAllText(tmp,JsonSerializer.Serialize(saved,new JsonSerializerOptions{IncludeFields=true}));File.Move(tmp,Journal,true);}
 static IntPtr View(){dynamic windows=Activator.CreateInstance(Type.GetTypeFromCLSID(new Guid("9BA05972-F6A8-11CF-A442-00A0C90A8F39"))!)!;object location=0,root=0;int hwnd;object desktop=windows.FindWindowSW(ref location,ref root,8,out hwnd,1);try{var service=(ServiceProvider)desktop;var sid=new Guid("4C96BE40-915C-11CF-99D3-00AA004AE837");var browserId=new Guid("000214E2-0000-0000-C000-000000000046");Marshal.ThrowExceptionForHR(service.QueryService(ref sid,ref browserId,out var browser));try{Marshal.ThrowExceptionForHR(Method<GetPtr>(browser,15)(browser,out var shellView));try{var iid=new Guid("CDE725B0-CCC9-4519-917E-325D72FAB4CE");Marshal.ThrowExceptionForHR(Marshal.QueryInterface(shellView,in iid,out var view));return view;}finally{Marshal.Release(shellView);}}finally{Marshal.Release(browser);}}finally{Marshal.ReleaseComObject(desktop);Marshal.ReleaseComObject(windows);}}
 static void WithItem(string path,Action<IntPtr,IntPtr> action){var view=View();try{var folderId=new Guid("000214E6-0000-0000-C000-000000000046");Marshal.ThrowExceptionForHR(Method<GetFolder>(view,5)(view,ref folderId,out var folder));try{Marshal.ThrowExceptionForHR(Method<GetCount>(view,7)(view,2,out var count));for(int i=0;i<count;i++){Marshal.ThrowExceptionForHR(Method<GetItem>(view,6)(view,i,out var child));try{var iid=new Guid("43826D1E-E718-42EE-BC55-A1E261C37BFE");if(SHCreateItemWithParent(IntPtr.Zero,folder,child,ref iid,out var item)<0)continue;try{if(Method<Name>(item,5)(item,0x80058000,out var text)<0)continue;string? name;try{name=Marshal.PtrToStringUni(text);}finally{Marshal.FreeCoTaskMem(text);}if(string.Equals(name,path,StringComparison.OrdinalIgnoreCase)){action(view,child);return;}}finally{Marshal.Release(item);}}finally{Marshal.FreeCoTaskMem(child);}}throw new IOException("未找到对应的桌面图标，未改变文件。");}finally{Marshal.Release(folder);}}finally{Marshal.Release(view);}}
 internal static Point Inspect(string path){Point p=default;WithItem(path,(v,i)=>Marshal.ThrowExceptionForHR(Method<GetPosition>(v,11)(v,i,out p)));return p;}
 internal static bool IsDesktop(string path){var parent=Path.GetDirectoryName(Path.GetFullPath(path));return new[]{Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),Environment.GetFolderPath(Environment.SpecialFolder.CommonDesktopDirectory)}.Any(d=>string.Equals(parent,d,StringComparison.OrdinalIgnoreCase));}
 internal static void Hide(string path){if(!IsDesktop(path)||saved.ContainsKey(path))return;WithItem(path,(view,item)=>{if(Method<AutoArrange>(view,14)(view)==0)throw new IOException("请先关闭桌面“自动排列图标”；软件不会替你更改桌面设置。");Marshal.ThrowExceptionForHR(Method<GetPosition>(view,11)(view,item,out var original));saved[path]=original;Persist();var off=new Point{X=-32000,Y=-32000};try{Marshal.ThrowExceptionForHR(Method<Position>(view,16)(view,1,[item],[off],0x80));Marshal.ThrowExceptionForHR(Method<GetPosition>(view,11)(view,item,out var actual));if(actual.X>-10000||actual.Y>-10000)throw new IOException("系统限制了图标位置，隐藏失败。");}catch{Method<Position>(view,16)(view,1,[item],[original],0x80);saved.Remove(path);Persist();throw;}});}
 internal static void EnsureHidden(string path){if(!saved.ContainsKey(path)||(!File.Exists(path)&&!Directory.Exists(path)))return;WithItem(path,(v,i)=>{Marshal.ThrowExceptionForHR(Method<GetPosition>(v,11)(v,i,out var p));if(p.X>-10000||p.Y>-10000){var off=new Point{X=-32000,Y=-32000};Marshal.ThrowExceptionForHR(Method<Position>(v,16)(v,1,[i],[off],0x80));Marshal.ThrowExceptionForHR(Method<GetPosition>(v,11)(v,i,out p));if(p.X>-10000||p.Y>-10000)throw new IOException("系统重新排列了图标，无法维持隐藏，请关闭自动排列。");}});}
 internal static void Restore(string path){if(!saved.TryGetValue(path,out var original))return;if(!File.Exists(path)&&!Directory.Exists(path)){saved.Remove(path);Persist();return;}WithItem(path,(v,i)=>{Marshal.ThrowExceptionForHR(Method<Position>(v,16)(v,1,[i],[original],0x80));Marshal.ThrowExceptionForHR(Method<GetPosition>(v,11)(v,i,out var actual));if(actual.X!=original.X||actual.Y!=original.Y)throw new IOException("图标未恢复到原位置，恢复记录已保留。");});saved.Remove(path);Persist();}
 internal static void Recover(){if(File.Exists(Journal))saved=JsonSerializer.Deserialize<Dictionary<string,Point>>(File.ReadAllText(Journal),new JsonSerializerOptions{IncludeFields=true})??new();foreach(var path in saved.Keys.ToArray()){if(!File.Exists(path)&&!Directory.Exists(path)){saved.Remove(path);Persist();}else Restore(path);}}
}



