using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
namespace DesktopBox;
internal static class MenuGlassTest {
 internal static void Run(Program app){app.ShutdownMode=ShutdownMode.OnExplicitShutdown;var canvas=new Canvas();for(int x=0;x<600;x+=8)canvas.Children.Add(new System.Windows.Shapes.Rectangle{Width=8,Height=400,Fill=x%16==0?Brushes.White:Brushes.RoyalBlue,Margin=new Thickness(x,0,0,0)});var background=new Window{Left=80,Top=80,Width=600,Height=400,WindowStyle=WindowStyle.None,Topmost=true,Content=canvas};background.Show();var settings=new Settings{Transparency=95,Frost=1};var menu=new ContextMenu{PlacementTarget=background,Placement=System.Windows.Controls.Primitives.PlacementMode.Relative,HorizontalOffset=40,VerticalOffset=40};Theme.Menu(menu,()=>settings);foreach(var label in new[]{"改名","锁定位置","视图 · 图标","视图 · 列表","视图 · 详细信息","删除盒子（保留文件）"})menu.Items.Add(new MenuItem{Header=label});menu.IsOpen=true;int stage=0;double low=0;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(900)};timer.Tick+=(_,_)=>{try{menu.UpdateLayout();var image=(Image)menu.Template.FindName("Frost",menu);if(image.Source is not BitmapSource source)throw new Exception("Menu background sampling unavailable");var width=source.PixelWidth;var bytes=new byte[width*source.PixelHeight*4];source.CopyPixels(bytes,width*4,0);var bitmap=new RenderTargetBitmap((int)Math.Ceiling(menu.ActualWidth),(int)Math.Ceiling(menu.ActualHeight),96,96,PixelFormats.Pbgra32);bitmap.Render(menu);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(bitmap));using(var file=File.Create(Path.Combine(AppContext.BaseDirectory,stage==0?"menu-low-frost.png":"menu-high-frost.png")))png.Save(file);var pixels=new byte[bitmap.PixelWidth*bitmap.PixelHeight*4];bitmap.CopyPixels(pixels,bitmap.PixelWidth*4,0);double sum=0,squared=0;int count=0;for(int x=12;x<bitmap.PixelWidth-12;x++){double red=pixels[(28*bitmap.PixelWidth+x)*4+2];sum+=red;squared+=red*red;count++;}var variance=squared/count-Math.Pow(sum/count,2);if(stage++==0){low=variance;if(low<100)throw new Exception("Controlled menu stripes not visible");settings.Frost=100;}else{if(variance>=low*0.25)throw new Exception("Menu frost did not blur background");if(((SolidColorBrush)menu.Background).Color.A!=13||((BlurEffect)image.Effect).Radius!=30)throw new Exception("Menu does not inherit settings");File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"menu-glass-test.txt"),$"PASS: actual menu transparent popup; controlled stripes blur variance {low:F2} -> {variance:F2}; global transparency 95% tint alpha 13; global frost 100% blur radius 30. Only own test stripes rendered.");Finish(0);}}catch(Exception ex){File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"menu-glass-test.txt"),ex.ToString());Finish(1);}};timer.Start();void Finish(int code){timer.Stop();menu.IsOpen=false;background.Close();app.Shutdown(code);}}
}
