using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using System.Windows.Media;
using Forms=System.Windows.Forms;
namespace DesktopBox;
public sealed class Program : System.Windows.Application {
 internal Settings Settings=new(); internal new List<BoxWindow> Windows=[]; Forms.NotifyIcon? tray; Manager? manager; DesktopLayer? desktop;readonly System.Windows.Threading.DispatcherTimer desktopTimer=new(){Interval=TimeSpan.FromMilliseconds(500)};bool hidden; bool ready; System.Threading.Mutex? mutex;
 [STAThread] public static void Main(string[] args){var testState=Environment.GetEnvironmentVariable("DESKTOPBOX_TEST_STATE");if(!string.IsNullOrEmpty(testState))Store.PathName=testState;if(args.Contains("--restore-icons")){try{DesktopIcons.Recover();DesktopLayer.RestoreNative();MessageBox.Show("已恢复有记录的原桌面图标。");}catch(Exception ex){MessageBox.Show("恢复失败，记录已保留："+ex.Message);}return;}if(args.Contains("--crash-test")){Environment.Exit(CrashTest.Run());return;} if(args.Length==2&&args[0]=="--watch"){try{try{System.Diagnostics.Process.GetProcessById(int.Parse(args[1])).WaitForExit();}catch(ArgumentException){}DesktopIcons.Recover();DesktopLayer.RestoreNative();}catch(Exception ex){File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"recovery-error.txt"),ex.ToString());}return;} if(args.Contains("--self-test")){Environment.Exit(SelfTest.Run());return;} var app=new Program();app.DispatcherUnhandledException+=(_,e)=>LogCrash("WPF dispatcher",e.Exception);AppDomain.CurrentDomain.UnhandledException+=(_,e)=>LogCrash("AppDomain",e.ExceptionObject);Environment.ExitCode=app.Run();}
 static void LogCrash(string source,object? error){try{var directory=Path.GetDirectoryName(Store.PathName)!;Directory.CreateDirectory(directory);File.AppendAllText(Path.Combine(directory,"crash.log"),$"[{DateTimeOffset.Now:O}] {source}{Environment.NewLine}{error}{Environment.NewLine}{new string('-',72)}{Environment.NewLine}");}catch{}}
 protected override void OnStartup(StartupEventArgs e){base.OnStartup(e);if(e.Args.Contains("--icon-test")){ShellTest.Run(this);return;}if(e.Args.Contains("--shell-test")){ShellTest.Run(this);return;}if(e.Args.Length==2&&e.Args[0]=="--layer-hold"){ShutdownMode=ShutdownMode.OnExplicitShutdown;Settings.Boxes.Add(new BoxConfig{Entries=[e.Args[1]]});RefreshDesktop();File.WriteAllText(e.Args[1]+".ready","ready");return;}if(e.Args.Contains("--menu-glass-test")){MenuGlassTest.Run(this);return;}if(e.Args.Contains("--glass-test")){GlassTest.Run(this);return;}if(e.Args.Contains("--ui-test")){UiTest.Run(this);return;}mutex=new(true,"Local\\DesktopBoxLY-v1",out var first);if(!first){Shutdown();return;}ShutdownMode=ShutdownMode.OnExplicitShutdown;
 try{Settings=Store.Load();}catch(Exception ex){MessageBox.Show("设置无法读取，已保留原文件。程序停止以避免覆盖。\n"+ex.Message);Shutdown();return;}
 try{DesktopIcons.Recover();DesktopLayer.RestoreNative();}catch(Exception ex){MessageBox.Show("桌面图标恢复失败，恢复记录已保留："+ex.Message);Shutdown();return;}
 ready=true;StartRecoveryHelper();foreach(var c in Settings.Boxes) Open(c);RefreshDesktop();desktopTimer.Tick+=(_,_)=>{try{RefreshDesktop();}catch(Exception ex){desktop?.Dispose();desktop=null;desktopTimer.Stop();MessageBox.Show(ex.Message,"桌面图标层已恢复，请重新启动软件");}};desktopTimer.Start();
 manager=new Manager(this); manager.Show(); tray=new Forms.NotifyIcon{Icon=AppIcons.TrayIcon(),Text="桌面盒子",Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("管理盒子",null,(_,_)=>Dispatcher.Invoke(()=>{manager.Show();manager.Activate();}));menu.Items.Add("显示 / 隐藏",null,(_,_)=>Dispatcher.Invoke(Toggle));menu.Items.Add("退出",null,(_,_)=>Dispatcher.Invoke(Shutdown));tray.ContextMenuStrip=menu;tray.DoubleClick+=(_,_)=>Dispatcher.Invoke(()=>{manager.Show();manager.Activate();});}
 void StartRecoveryHelper(){var exe=Environment.ProcessPath!;var watchArgs="--watch "+Environment.ProcessId; if(Path.GetFileNameWithoutExtension(exe).Equals("dotnet",StringComparison.OrdinalIgnoreCase)) watchArgs="\""+typeof(Program).Assembly.Location+"\" "+watchArgs;System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(exe,watchArgs){UseShellExecute=false,CreateNoWindow=true});}
 internal void Open(BoxConfig c){var w=new BoxWindow(this,c);Windows.Add(w);w.Show();}
 internal void SetFrost(double value){Settings.Frost=Math.Clamp(value,0,100);foreach(var box in Windows)box.ApplyTransparency();manager?.ApplyMaterial();Save();}
 internal void SetTransparency(double value){Settings.Transparency=Math.Clamp(value,0,95);foreach(var box in Windows)box.ApplyTransparency();manager?.ApplyMaterial();Save();}
 internal void SetIntervals(int backgroundMs,int fileMs){Settings.BackgroundIntervalMs=Math.Clamp(backgroundMs,50,5000);Settings.FileIntervalMs=Math.Clamp(fileMs,250,60000);foreach(var box in Windows)box.ApplyTiming();manager?.ApplyMaterial();Save();}
 internal DesktopLayer? Desktop=>desktop;
 internal void RefreshDesktop(){desktop??=new DesktopLayer(()=>Settings,()=>Windows);desktop.Refresh();}
 internal void RefreshManager()=>manager?.Refresh();
 internal void Save(){try{Store.Save(Settings);}catch(Exception ex){MessageBox.Show("保存失败："+ex.Message);}}
 internal void Toggle(){hidden=!hidden;if(hidden){foreach(var w in Windows){w.Topmost=false;w.Hide();}RefreshDesktop();return;}foreach(var w in Windows){w.Topmost=false;w.Show();}Windows.LastOrDefault()?.Activate();Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Background,new Action(RefreshDesktop));}
 internal void Delete(BoxWindow w){if(MessageBox.Show("删除盒子只移除配置，所有真实文件保留。继续？","删除盒子",MessageBoxButton.YesNo)!=MessageBoxResult.Yes)return;Settings.Boxes.Remove(w.Config);Windows.Remove(w);w.DisposeAndClose();RefreshDesktop();Save();manager?.Refresh();}
 protected override void OnExit(ExitEventArgs e){desktopTimer.Stop();desktop?.Dispose();desktop=null;foreach(var w in Windows.ToArray())w.DisposeAndClose();if(ready)Save();tray?.Dispose();mutex?.Dispose();base.OnExit(e);}
}
internal sealed class Manager:Window {
 internal readonly Border DragHeader=new(){Background=Brushes.Transparent,Margin=new Thickness(-22,-22,-22,4),Padding=new Thickness(22,14,22,10)};internal Button MinimizeButton=null!;
 readonly Program app; readonly StackPanel list=new();GlassSurface? material;internal readonly TextBox BackgroundIntervalEditor=new(){Width=70,Style=Theme.EditorStyle,Padding=new Thickness(6,4,6,4)};internal readonly TextBox FileIntervalEditor=new(){Width=70,Style=Theme.EditorStyle,Padding=new Thickness(6,4,6,4)}; internal readonly Slider FrostSlider=new(){Minimum=0,Maximum=100,Style=Theme.SliderStyle}; readonly TextBlock frostValue=new(){Width=38,Foreground=Theme.Muted,VerticalAlignment=VerticalAlignment.Center}; internal readonly Slider TransparencySlider=new(){Minimum=0,Maximum=95,Style=Theme.SliderStyle}; readonly TextBlock transparencyValue=new(){Width=38,Foreground=Theme.Muted,VerticalAlignment=VerticalAlignment.Center}; IntPtr handle;
 internal Manager(Program app,bool registerHotkey=true){this.app=app;Icon=AppIcons.WindowIcon;Title="桌面盒子 · 管理";Width=480;Height=760;MinWidth=420;MinHeight=440;WindowStyle=WindowStyle.None;ResizeMode=ResizeMode.NoResize;AllowsTransparency=true;Background=Brushes.Transparent;Foreground=Theme.Text;
 var panel=new StackPanel{Margin=new Thickness(22),Effect=new System.Windows.Media.Effects.DropShadowEffect{Color=Colors.Black,BlurRadius=2,ShadowDepth=1,Opacity=0.55}};var scroll=new ScrollViewer{Content=panel,VerticalScrollBarVisibility=ScrollBarVisibility.Hidden,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};var header=new DockPanel{Background=Brushes.Transparent,Margin=new Thickness(0,0,0,4)};var close=Button("×",Hide);close.Width=30;close.Padding=new Thickness(0);close.FontSize=22;close.HorizontalContentAlignment=HorizontalAlignment.Center;close.Background=Brushes.Transparent;close.BorderThickness=new Thickness(0);DockPanel.SetDock(close,Dock.Right);header.Children.Add(close);MinimizeButton=Button("−",()=>WindowState=WindowState.Minimized);MinimizeButton.ToolTip="最小化";MinimizeButton.Width=30;MinimizeButton.Padding=new Thickness(0);MinimizeButton.FontSize=22;MinimizeButton.HorizontalContentAlignment=HorizontalAlignment.Center;MinimizeButton.Background=Brushes.Transparent;MinimizeButton.BorderThickness=new Thickness(0);DockPanel.SetDock(MinimizeButton,Dock.Right);header.Children.Add(MinimizeButton);header.Children.Add(new TextBlock{Text="桌面盒子",FontSize=26,VerticalAlignment=VerticalAlignment.Center});DragHeader.Child=header;DragHeader.PreviewMouseLeftButtonDown+=(_,e)=>{var node=e.OriginalSource as DependencyObject;while(node!=null){if(node is System.Windows.Controls.Primitives.ButtonBase)return;node=VisualTreeHelper.GetParent(node);}try{DragMove();e.Handled=true;}catch(InvalidOperationException){}};panel.Children.Add(DragHeader);panel.Children.Add(new TextBlock{Text="普通盒子保留文件位置；映射盒子拖入会移动文件。\n图标隐藏使用实验桌面层，退出恢复系统桌面。",Margin=new Thickness(0,12,0,12),TextWrapping=TextWrapping.Wrap});
 var appearance=new DockPanel{Margin=new Thickness(0,4,0,16)};var label=new TextBlock{Text="统一透明度",Width=72,Foreground=Theme.Muted,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,12,0)};DockPanel.SetDock(label,Dock.Left);appearance.Children.Add(label);DockPanel.SetDock(transparencyValue,Dock.Right);appearance.Children.Add(transparencyValue);appearance.Children.Add(TransparencySlider);TransparencySlider.Value=Math.Clamp(app.Settings.Transparency,0,95);transparencyValue.Text=Math.Round(TransparencySlider.Value)+"%";TransparencySlider.ToolTip="同时调整所有盒子的玻璃背景";TransparencySlider.ValueChanged+=(_,_)=>{transparencyValue.Text=Math.Round(TransparencySlider.Value)+"%";app.SetTransparency(TransparencySlider.Value);ApplyMaterial();};panel.Children.Add(appearance);var frostRow=new DockPanel{Margin=new Thickness(0,0,0,6)};var frostLabel=new TextBlock{Text="磨砂浓度",Width=72,Foreground=Theme.Muted,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,12,0)};DockPanel.SetDock(frostLabel,Dock.Left);frostRow.Children.Add(frostLabel);DockPanel.SetDock(frostValue,Dock.Right);frostRow.Children.Add(frostValue);frostRow.Children.Add(FrostSlider);FrostSlider.Value=Math.Clamp(app.Settings.Frost,0,100);frostValue.Text=Math.Round(FrostSlider.Value)+"%";FrostSlider.ToolTip="背景仅在本机内存中采样和模糊，不保存或上传画面";FrostSlider.ValueChanged+=(_,_)=>{frostValue.Text=Math.Round(FrostSlider.Value)+"%";app.SetFrost(FrostSlider.Value);ApplyMaterial();};panel.Children.Add(frostRow);panel.Children.Add(new TextBlock{Text="0% 为清透玻璃。开启磨砂会影响截图和录屏；需截盒子时先调回 0%。",Foreground=Theme.Muted,FontSize=11,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,14)});
 BackgroundIntervalEditor.Text=Math.Clamp(app.Settings.BackgroundIntervalMs,50,5000).ToString();FileIntervalEditor.Text=Math.Clamp(app.Settings.FileIntervalMs,250,60000).ToString();AddTimingRow(panel,"磨砂采样",BackgroundIntervalEditor,[50,100,200,500,1000]);AddTimingRow(panel,"列表检查",FileIntervalEditor,[500,1000,2000,5000,10000]);panel.Children.Add(new TextBlock{Text="间隔单位：毫秒；列表同时响应文件夹变化。",Foreground=Theme.Muted,FontSize=11,Margin=new Thickness(0,2,0,12)});material=new GlassSurface(this,scroll,()=>app.Settings);
 panel.Children.Add(Button("＋ 普通盒子",()=>Create(false)));panel.Children.Add(Button("＋ 文件夹映射",()=>Create(true)));panel.Children.Add(Button("显示 / 隐藏所有盒子",app.Toggle));panel.Children.Add(Button("设置全局快捷键",ChangeHotkey));panel.Children.Add(new TextBlock{Text="默认 Ctrl + Alt + B；唤出盒子到前台，切换到其他应用后盒子可被覆盖。\n安全桌面、锁屏及部分独占全屏不可覆盖。",Margin=new Thickness(0,10,0,12)});panel.Children.Add(list);panel.Children.Add(Button("退出软件",app.Shutdown));
 SourceInitialized+=(_,_)=>{handle=new WindowInteropHelper(this).Handle;HwndSource.FromHwnd(handle).AddHook(Hook);if(registerHotkey&&!Native.RegisterHotKey(handle,1,app.Settings.Modifiers|0x4000,app.Settings.Key))MessageBox.Show("快捷键已被占用，请在设置中修改。");};Closing+=(_,e)=>{e.Cancel=true;Hide();};Refresh();}
 internal void ApplyMaterial()=>material?.Apply();
 internal byte TintAlpha=>material?.TintAlpha??0;
 internal void CommitIntervals(){if(!int.TryParse(BackgroundIntervalEditor.Text,out var background)||background<50||background>5000||!int.TryParse(FileIntervalEditor.Text,out var file)||file<250||file>60000){BackgroundIntervalEditor.Text=app.Settings.BackgroundIntervalMs.ToString();FileIntervalEditor.Text=app.Settings.FileIntervalMs.ToString();MessageBox.Show("磨砂采样请输入50–5000毫秒；列表检查请输入250–60000毫秒的整数。");return;}app.SetIntervals(background,file);ApplyMaterial();}
 void AddTimingRow(Panel panel,string label,TextBox editor,int[] presets){var row=new DockPanel{Margin=new Thickness(0,3,0,4)};var title=new TextBlock{Text=label,Width=72,Foreground=Theme.Muted,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,12,0)};DockPanel.SetDock(title,Dock.Left);row.Children.Add(title);var choice=Button("常用 ▾",()=>{var menu=new ContextMenu();Theme.Menu(menu,()=>app.Settings);foreach(var value in presets){var item=new MenuItem{Header=value+" 毫秒"};item.Click+=(_,_)=>{editor.Text=value.ToString();CommitIntervals();};menu.Items.Add(item);}menu.IsOpen=true;});choice.Margin=new Thickness(8,0,0,0);choice.Padding=new Thickness(8,4,8,4);DockPanel.SetDock(choice,Dock.Right);row.Children.Add(choice);row.Children.Add(editor);editor.HorizontalAlignment=HorizontalAlignment.Left;editor.ToolTip=label=="磨砂采样"?"50–5000毫秒，默认200毫秒":"250–60000毫秒，默认2000毫秒";editor.LostKeyboardFocus+=(_,_)=>CommitIntervals();editor.KeyDown+=(_,e)=>{if(e.Key==System.Windows.Input.Key.Enter){CommitIntervals();e.Handled=true;}};panel.Children.Add(row);}
 IntPtr Hook(IntPtr h,int msg,IntPtr w,IntPtr l,ref bool handled){if(msg==0x312){app.Toggle();handled=true;}return IntPtr.Zero;}
 internal static System.Windows.Controls.Button Button(string text,Action action){var b=new System.Windows.Controls.Button{Content=text,Margin=new Thickness(0,4,0,4),Padding=new Thickness(10,7,10,7),Style=Theme.ButtonStyle,HorizontalContentAlignment=HorizontalAlignment.Left};b.Click+=(_,_)=>action();return b;}
 void Create(bool map){var folder=map?PickFolder():null;if(map&&folder==null)return;var c=new BoxConfig{Name=map?Path.GetFileName(folder!):"普通盒子",Folder=folder,X=80+app.Windows.Count*30,Y=100+app.Windows.Count*30};app.Settings.Boxes.Add(c);app.Open(c);app.Save();Refresh();}
 internal void Refresh(){list.Children.Clear();foreach(var w in app.Windows.ToArray()){var b=Button(w.Config.Name+(w.Config.Folder==null?" · 普通":" · 映射"),()=>{w.Show();w.Activate();});list.Children.Add(b);}}
 internal static string? PickFolder(){using var d=new Forms.FolderBrowserDialog{Description="选择映射文件夹",UseDescriptionForTitle=true};return d.ShowDialog()==Forms.DialogResult.OK?d.SelectedPath:null;}
 internal static string? Ask(Window owner,string title,string initial){var d=new Window{Owner=owner,Title=title,Width=360,Height=180,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize};var p=new StackPanel{Margin=new Thickness(15)};var t=new TextBox{Text=initial,Margin=new Thickness(0,8,0,12)};p.Children.Add(t);p.Children.Add(Button("确定",()=>{d.DialogResult=true;}));d.Content=p;return d.ShowDialog()==true?t.Text.Trim():null;}
 void ChangeHotkey(){var s=Ask(this,"快捷键，例如 Ctrl+Alt+B","Ctrl+Alt+B");if(s==null)return;uint mods=0,key=0;foreach(var part in s.Split('+')){var p=part.Trim().ToUpperInvariant();if(p=="CTRL")mods|=2;else if(p=="ALT")mods|=1;else if(p=="SHIFT")mods|=4;else if(p=="WIN")mods|=8;else if(p.Length==1&&char.IsAsciiLetterOrDigit(p[0]))key=p[0];else{MessageBox.Show("使用 Ctrl/Alt/Shift/Win 加一个字母或数字。");return;}}if(mods==0||key==0){MessageBox.Show("需要修饰键和字母/数字。");return;}Native.UnregisterHotKey(handle,1);if(!Native.RegisterHotKey(handle,1,mods|0x4000,key)){Native.RegisterHotKey(handle,1,app.Settings.Modifiers|0x4000,app.Settings.Key);MessageBox.Show("快捷键被占用，保留原快捷键。");return;}app.Settings.Modifiers=mods;app.Settings.Key=key;app.Save();}
}
