using System.IO;
using System.Runtime.InteropServices;
using System.Windows.Threading;
namespace DesktopBox;
internal static class ShellTest {
 internal static void Run(Program app){app.ShutdownMode=System.Windows.ShutdownMode.OnExplicitShutdown;var root=Path.Combine(Path.GetTempPath(),"DesktopBox-ShellTest-"+Guid.NewGuid());Directory.CreateDirectory(root);Store.PathName=Path.Combine(root,"state.json");var target=Path.Combine(root,"target.txt");File.WriteAllText(target,"unchanged");var shortcut=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"DesktopBox-ShellTest-"+Guid.NewGuid()+".lnk");BoxWindow? box=null;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(500)};DesktopIcons.Point original=default;int steps=0;bool recovered=false;
 try{dynamic shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell")!)!;try{dynamic link=shell.CreateShortcut(shortcut);try{link.TargetPath=target;link.Save();}finally{Marshal.ReleaseComObject(link);}}finally{Marshal.ReleaseComObject(shell);}Thread.Sleep(2000);original=DesktopIcons.Inspect(shortcut);var removed=Path.Combine(root,"removed.txt");File.WriteAllText(removed,"temporary");File.Delete(removed);if(DesktopLayer.TryDragData(removed,out _))throw new Exception("Deleted drag entry accepted");if(DesktopLayer.TryDragData("::{00000000-0000-0000-0000-000000000000}",out _))throw new Exception("Invalid namespace accepted");if(!DesktopLayer.TryDragData(shortcut,out var checkedData)||checkedData==null||!ShellItems.Read(checkedData).Contains(shortcut))throw new Exception("Valid desktop drag rejected");var systems=new[]{"::{645FF040-5081-101B-9F08-00AA002F954E}","::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}","::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}"};foreach(var id in systems){if(!ShellItems.Exists(id)||ShellItems.DisplayName(id)=="系统入口"||ShellIcons.Get(id)==null)throw new Exception("System entry metadata unavailable");}var source=ShellItems.CreateData(systems.Append(shortcut).ToArray());var paths=ShellItems.Read(source);if(paths.Count!=4||!paths.Contains(shortcut,StringComparer.OrdinalIgnoreCase)||paths.Contains(target,StringComparer.OrdinalIgnoreCase))throw new Exception("Shell drag data did not preserve shortcut identity");var config=new BoxConfig{Name="系统入口测试"};app.Settings.Boxes.Add(config);box=new BoxWindow(app,config);app.Windows.Add(box);box.Show();var errors=box.ReceiveDrop(source);if(errors.Count>0||config.Entries.Count!=4)throw new Exception("Box rejected shell drop: "+string.Join(";",errors));app.RefreshDesktop();AssertState();timer.Tick+=(_,_)=>{try{app.RefreshDesktop();AssertState();if(++steps<6)return;app.Settings.Boxes.Clear();app.RefreshDesktop();var restored=DesktopIcons.Inspect(shortcut);if(!DesktopLayer.NativeVisible||restored.X!=original.X||restored.Y!=original.Y||File.ReadAllText(target)!="unchanged")throw new Exception("Native desktop restoration failed");recovered=true;File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"shell-test.txt"),"PASS: removed entry and invalid namespace drag safely rejected; valid shortcut drag retained; Recycle Bin, Network, Control Panel metadata and icons; Shell drag data preserves shortcut identity; desktop child layer attached; collected entries excluded; original native list remains hidden across 3 seconds; non-collected entries preserved; normal exit restores original visibility and exact shortcut position; target unchanged; isolated test state.");Cleanup();app.Shutdown();}catch(Exception ex){Fail(ex);}};timer.Start();}
 catch(Exception ex){Fail(ex);}
 void AssertState(){if(DesktopLayer.NativeVisible||app.Desktop==null||!app.Desktop.Attached)throw new Exception("Native desktop icons are still visible or layer detached");if(Math.Abs(app.Desktop.RenderedIconPixels-DesktopIcons.IconSize())>0.01)throw new Exception("Replacement desktop icon size differs from native");var native=DesktopIcons.ReadAll();var collected=app.Settings.Boxes.SelectMany(x=>x.Entries).ToHashSet(StringComparer.OrdinalIgnoreCase);if(native.Where(x=>collected.Contains(x.Id)).Any(x=>app.Desktop.Contains(x.Id)))throw new Exception("Collected icon duplicated in desktop layer");if(app.Desktop.DisplayedCount!=native.Count(x=>!collected.Contains(x.Id)))throw new Exception("Uncollected icons missing");var point=DesktopIcons.Inspect(shortcut);if(point.X!=original.X||point.Y!=original.Y)throw new Exception("Native icon position was changed");}
 void Fail(Exception ex){File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"shell-test.txt"),ex.ToString());Cleanup();app.Shutdown(1);}
 void Cleanup(){timer.Stop();app.Settings.Boxes.Clear();try{app.RefreshDesktop();recovered=true;}catch{}box?.DisposeAndClose();app.Windows.Clear();if(recovered){File.Delete(shortcut);Directory.Delete(root,true);}}
 }
}

