using System.IO;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
namespace DesktopBox;
internal static class UiTest {
 internal static void Run(Program app){app.ShutdownMode=ShutdownMode.OnExplicitShutdown;var folder=Path.Combine(Path.GetTempPath(),"DesktopBox-UI-"+Guid.NewGuid());Directory.CreateDirectory(folder);File.WriteAllText(Path.Combine(folder,"会议记录.txt"),"test");Directory.CreateDirectory(Path.Combine(folder,"设计资料"));Store.PathName=Path.Combine(folder,"ui-settings.json");var config=new BoxConfig{Name="工作资料",Folder=folder,Width=480,Height=430};var desktopFile=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory),"DesktopBox-Lifecycle-"+Guid.NewGuid()+".txt");File.WriteAllText(desktopFile,"unchanged");Thread.Sleep(2000);var original=DesktopIcons.Inspect(desktopFile);var virtualConfig=new BoxConfig{Name="普通测试",Locked=true,Entries=[desktopFile]};var virtualWindow=new BoxWindow(app,virtualConfig);virtualWindow.Show();if(virtualWindow.ResizeMode!=ResizeMode.NoResize)throw new Exception("Lock not applied");var window=new BoxWindow(app,config);window.Show();var timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};timer.Tick+=(_,_)=>{timer.Stop();try{foreach(var view in new[]{"图标","列表","详细信息"}){config.View=view;window.Refresh();window.UpdateLayout();var bmp=new RenderTargetBitmap((int)window.ActualWidth,(int)window.ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(window);var png=new PngBitmapEncoder();png.Frames.Add(BitmapFrame.Create(bmp));using var output=File.Create(Path.Combine(AppContext.BaseDirectory,"ui-"+view+".png"));png.Save(output);}window.DisposeAndClose();virtualWindow.DisposeAndClose();var restored=DesktopIcons.Inspect(desktopFile);if(restored.X!=original.X||restored.Y!=original.Y||File.ReadAllText(desktopFile)!="unchanged")throw new Exception("Window lifecycle restoration failed");File.Delete(desktopFile);Directory.Delete(folder,true);File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"ui-test.txt"),"PASS: windows shown, three views rendered, position lock applied, ordinary box close restored exact desktop icon position and preserved file; temporary files removed");app.Shutdown();}catch(Exception ex){File.WriteAllText(Path.Combine(AppContext.BaseDirectory,"ui-test.txt"),ex.ToString());app.Shutdown(1);}};timer.Start();}
}


